/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClientRecord = IDL.Record({
  'senhaCliente' : IDL.Text,
  'senhaVps' : IDL.Text,
  'nome' : IDL.Text,
  'userVps' : IDL.Text,
  'ipVps' : IDL.Text,
  'idLuid' : IDL.Text,
  'plano' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearGlobalAnnouncement' : IDL.Func([], [], []),
  'createClientRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteClientRecord' : IDL.Func([IDL.Text], [], []),
  'getAllClientRecords' : IDL.Func([], [IDL.Vec(ClientRecord)], ['query']),
  'getClientRecord' : IDL.Func([IDL.Text], [ClientRecord], ['query']),
  'getGlobalAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
  'getNetworkMonitoringStatus' : IDL.Func([], [IDL.Text], ['query']),
  'setGlobalAnnouncement' : IDL.Func([IDL.Text], [], []),
  'updateClientRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNetworkMonitoringStatus' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClientRecord = IDL.Record({
    'senhaCliente' : IDL.Text,
    'senhaVps' : IDL.Text,
    'nome' : IDL.Text,
    'userVps' : IDL.Text,
    'ipVps' : IDL.Text,
    'idLuid' : IDL.Text,
    'plano' : IDL.Text,
  });
  
  return IDL.Service({
    'clearGlobalAnnouncement' : IDL.Func([], [], []),
    'createClientRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteClientRecord' : IDL.Func([IDL.Text], [], []),
    'getAllClientRecords' : IDL.Func([], [IDL.Vec(ClientRecord)], ['query']),
    'getClientRecord' : IDL.Func([IDL.Text], [ClientRecord], ['query']),
    'getGlobalAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
    'getNetworkMonitoringStatus' : IDL.Func([], [IDL.Text], ['query']),
    'setGlobalAnnouncement' : IDL.Func([IDL.Text], [], []),
    'updateClientRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNetworkMonitoringStatus' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };