/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientRecord {
  'senhaCliente' : string,
  'senhaVps' : string,
  'nome' : string,
  'userVps' : string,
  'ipVps' : string,
  'idLuid' : string,
  'plano' : string,
}
export interface _SERVICE {
  'clearGlobalAnnouncement' : ActorMethod<[], undefined>,
  'createClientRecord' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'deleteClientRecord' : ActorMethod<[string], undefined>,
  'getAllClientRecords' : ActorMethod<[], Array<ClientRecord>>,
  'getClientRecord' : ActorMethod<[string], ClientRecord>,
  'getGlobalAnnouncement' : ActorMethod<[], string>,
  'getNetworkMonitoringStatus' : ActorMethod<[], string>,
  'setGlobalAnnouncement' : ActorMethod<[string], undefined>,
  'updateClientRecord' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateNetworkMonitoringStatus' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];