/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientRecord {
  'senhaCliente' : string,
  'senhaVps' : string,
  'nome' : string,
  'userVps' : string,
  'ipVps' : string,
  'idLuid' : string,
  'plano' : string,
}
export interface Employee {
  'password' : string,
  'name' : string,
  'role' : string,
  'employeeId' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'employeeId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateEmployee' : ActorMethod<[string, string], boolean>,
  'clearGlobalAnnouncement' : ActorMethod<[], undefined>,
  'createClientRecord' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'createEmployee' : ActorMethod<[string, string, string, string], undefined>,
  'deleteClientRecord' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'getAllClientRecords' : ActorMethod<[], Array<ClientRecord>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientRecord' : ActorMethod<[string], ClientRecord>,
  'getGlobalAnnouncement' : ActorMethod<[], string>,
  'getNetworkMonitoringStatus' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGlobalAnnouncement' : ActorMethod<[string], undefined>,
  'updateClientRecord' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateEmployee' : ActorMethod<[string, string, string, string], undefined>,
  'updateNetworkMonitoringStatus' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];