/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
  'receiver' : string,
}
export type ChatSystemStatus = { 'offline' : null } |
  { 'online' : null };
export interface ClientRecord {
  'senhaCliente' : string,
  'senhaVps' : string,
  'nome' : string,
  'vmStatus' : VMStatus,
  'userVps' : string,
  'operatingSystem' : OperatingSystem,
  'planExpiry' : Time,
  'ipVps' : string,
  'idLuid' : string,
  'plano' : string,
}
export interface Notification { 'message' : string, 'timestamp' : bigint }
export type OperatingSystem = { 'ubuntu' : null } |
  { 'windows' : null };
export type Time = bigint;
export type VMStatus = { 'maintenance' : null } |
  { 'offline' : null } |
  { 'online' : null };
export interface _SERVICE {
  'addNotification' : ActorMethod<[string, string], undefined>,
  'clearGlobalAnnouncement' : ActorMethod<[], undefined>,
  'clearMessages' : ActorMethod<[string], undefined>,
  'clearNotifications' : ActorMethod<[string], undefined>,
  'createClientRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      VMStatus,
      OperatingSystem,
      Time,
    ],
    undefined
  >,
  'deleteClientRecord' : ActorMethod<[string], undefined>,
  'getAllClientRecords' : ActorMethod<[], Array<ClientRecord>>,
  'getChatSystemStatus' : ActorMethod<[], ChatSystemStatus>,
  'getClientRecord' : ActorMethod<[string], ClientRecord>,
  'getGlobalAnnouncement' : ActorMethod<[], string>,
  'getMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getNetworkMonitoringStatus' : ActorMethod<[], string>,
  'getNotifications' : ActorMethod<[string], Array<Notification>>,
  'sendMessage' : ActorMethod<[string, string, string], undefined>,
  'setChatSystemStatus' : ActorMethod<[ChatSystemStatus], undefined>,
  'setGlobalAnnouncement' : ActorMethod<[string], undefined>,
  'updateClientRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      VMStatus,
      OperatingSystem,
      Time,
    ],
    undefined
  >,
  'updateNetworkMonitoringStatus' : ActorMethod<[string], undefined>,
  'updateVMStatus' : ActorMethod<[string, VMStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];