/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChatMessage {
    sender: string;
    message: string;
    timestamp: bigint;
}
export interface Notification {
    message: string;
    timestamp: bigint;
}
export interface ClientRecord {
    senhaCliente: string;
    senhaVps: string;
    nome: string;
    vmStatus: VMStatus;
    userVps: string;
    ipVps: string;
    idLuid: string;
    plano: string;
}
export enum VMStatus {
    maintenance = "maintenance",
    offline = "offline",
    online = "online"
}
export interface backendInterface {
    addAdminAccount(username: string, password: string): Promise<void>;
    addNotification(clientId: string, message: string): Promise<void>;
    adminLogin(username: string, password: string): Promise<boolean>;
    clearChatMessages(userId: string): Promise<void>;
    clearGlobalAnnouncement(): Promise<void>;
    clearNotifications(clientId: string): Promise<void>;
    createClientRecord(idLuid: string, nome: string, senhaCliente: string, ipVps: string, userVps: string, senhaVps: string, plano: string, vmStatus: VMStatus): Promise<void>;
    deleteClientRecord(idLuid: string): Promise<void>;
    getAllClientRecords(): Promise<Array<ClientRecord>>;
    getChatMessages(userId: string): Promise<Array<ChatMessage>>;
    getClientRecord(idLuid: string): Promise<ClientRecord>;
    getGlobalAnnouncement(): Promise<string>;
    getNetworkMonitoringStatus(): Promise<string>;
    getNotifications(clientId: string): Promise<Array<Notification>>;
    sendMessage(sender: string, message: string): Promise<void>;
    setGlobalAnnouncement(announcement: string): Promise<void>;
    updateClientRecord(idLuid: string, nome: string, senhaCliente: string, ipVps: string, userVps: string, senhaVps: string, plano: string, vmStatus: VMStatus): Promise<void>;
    updateNetworkMonitoringStatus(status: string): Promise<void>;
    updateVMStatus(idLuid: string, status: VMStatus): Promise<void>;
}
import type { ClientRecord as _ClientRecord, VMStatus as _VMStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdminAccount(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminAccount(arg0, arg1);
            return result;
        }
    }
    async addNotification(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async clearChatMessages(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatMessages(arg0);
            return result;
        }
    }
    async clearGlobalAnnouncement(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearGlobalAnnouncement();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearGlobalAnnouncement();
            return result;
        }
    }
    async clearNotifications(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearNotifications(arg0);
            return result;
        }
    }
    async createClientRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: VMStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_VMStatus_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_VMStatus_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async deleteClientRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClientRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClientRecord(arg0);
            return result;
        }
    }
    async getAllClientRecords(): Promise<Array<ClientRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClientRecords();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClientRecords();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getClientRecord(arg0: string): Promise<ClientRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientRecord(arg0);
                return from_candid_ClientRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientRecord(arg0);
            return from_candid_ClientRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalAnnouncement(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalAnnouncement();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalAnnouncement();
            return result;
        }
    }
    async getNetworkMonitoringStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetworkMonitoringStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetworkMonitoringStatus();
            return result;
        }
    }
    async getNotifications(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setGlobalAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGlobalAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGlobalAnnouncement(arg0);
            return result;
        }
    }
    async updateClientRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: VMStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_VMStatus_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_VMStatus_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateNetworkMonitoringStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNetworkMonitoringStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNetworkMonitoringStatus(arg0);
            return result;
        }
    }
    async updateVMStatus(arg0: string, arg1: VMStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVMStatus(arg0, to_candid_VMStatus_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVMStatus(arg0, to_candid_VMStatus_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ClientRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientRecord): ClientRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_VMStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VMStatus): VMStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    senhaCliente: string;
    senhaVps: string;
    nome: string;
    vmStatus: _VMStatus;
    userVps: string;
    ipVps: string;
    idLuid: string;
    plano: string;
}): {
    senhaCliente: string;
    senhaVps: string;
    nome: string;
    vmStatus: VMStatus;
    userVps: string;
    ipVps: string;
    idLuid: string;
    plano: string;
} {
    return {
        senhaCliente: value.senhaCliente,
        senhaVps: value.senhaVps,
        nome: value.nome,
        vmStatus: from_candid_VMStatus_n6(_uploadFile, _downloadFile, value.vmStatus),
        userVps: value.userVps,
        ipVps: value.ipVps,
        idLuid: value.idLuid,
        plano: value.plano
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maintenance: null;
} | {
    offline: null;
} | {
    online: null;
}): VMStatus {
    return "maintenance" in value ? VMStatus.maintenance : "offline" in value ? VMStatus.offline : "online" in value ? VMStatus.online : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientRecord>): Array<ClientRecord> {
    return value.map((x)=>from_candid_ClientRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_VMStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VMStatus): _VMStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VMStatus): {
    maintenance: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == VMStatus.maintenance ? {
        maintenance: null
    } : value == VMStatus.offline ? {
        offline: null
    } : value == VMStatus.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
